#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Load current theme files to get colors for bspwm
source "$BSPDIR"/themes/current.bash

## Get the wallpaper from theme file
sxhkd &
#feh --bg-fill /home/kana/Imágenes/Fondos/06.jpg
#feh --bg-fill /home/kana/Imágenes/Fondos/07.jpg
feh --bg-fill /home/kana/Imágenes/Fondos/21.jpg
## Get the colors from theme file
BACKGROUND="$background"
GREEN="$color2"
BLUE="$color4"
MAGENTA="$color5"

## Bspwm appearance
CURRENT_BORDER='1'
CURRENT_GAP='10'
CURRENT_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manager Workspaces
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

## Apply bspwm configurations
bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a gnome-terminal desktop='^1' follow=on focus=on

## 2 > web (always open web browser on workspace-2)
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on
bspc rule -a Chrome desktop='^2' follow=on focus=on

## 3 > files (always open file manager on workspace-3)
bspc rule -a Pcmanfm desktop='^3' follow=on focus=on
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a qBittorrent desktop='^3' follow=on focus=on

## 4 > code (always open editors on workspace-4)
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a code-oss desktop='^4' follow=on focus=on
bspc rule -a code desktop='^4' follow=on focus=on

## 5 > office and docs (always open office/doc apps on workspace-5)
bspc rule -a Gucharmap desktop='^5' follow=on focus=on
bspc rule -a Atril desktop='^5' follow=on focus=on
bspc rule -a Evince desktop='^5' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^5' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^5' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^5' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^5' follow=on focus=on
bspc rule -a libreoffice desktop='^5' follow=on focus=on
bspc rule -a Soffice desktop='^5' follow=on focus=on
bspc rule -a libreofficedev desktop='^5' follow=on focus=on
bspc rule -a soffice desktop='^5' follow=on focus=on

## 6 > communication (always open communication apps on workspace-6)
bspc rule -a Thunderbird desktop='^6' follow=on focus=on
bspc rule -a TelegramDesktop desktop='^6' follow=on focus=on
bspc rule -a Hexchat desktop='^6' follow=on focus=on

## 7 > media (always open media apps on workspace-7)
bspc rule -a Audacity desktop='^7' state=floating follow=on focus=on
bspc rule -a Music desktop='^7' state=floating follow=on focus=on
bspc rule -a MPlayer desktop='^7' state=floating follow=on focus=on
bspc rule -a Lxmusic desktop='^7' state=floating follow=on focus=on
bspc rule -a Inkscape desktop='^7' state=floating follow=on focus=on
bspc rule -a krita desktop='^7' state=floating follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^7' state=floating follow=on focus=on
bspc rule -a obs desktop='^7' state=floating follow=on focus=on

## 8 > system (always open system apps on workspace-8)
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a Lxappearance desktop='^8' state=floating follow=on focus=on
bspc rule -a Lxtask desktop='^8' state=floating follow=on focus=on
bspc rule -a Lxrandr desktop='^8' state=floating follow=on focus=on
bspc rule -a Arandr desktop='^8' state=floating follow=on focus=on
bspc rule -a System-config-printer.py desktop='^8' state=floating follow=on focus=on
bspc rule -a Pavucontrol desktop='^8' state=floating follow=on focus=on
bspc rule -a Exo-helper-1 desktop='^8' state=floating follow=on focus=on
bspc rule -a Xfce4-power-manager-settings desktop='^8' state=floating follow=on focus=on

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper

# Start mpd
exec mpd &


# Start bspwm scripts

bspcolors
bspbar
bspcomp
bspdunst
bspfloat &

# Cambia la polyBar al inicio

## Polybar config directory
PBDIR="$HOME/.config/bspwm/polybar"

bash "$PBDIR"/launch.sh --hack
bash "$PBDIR"/hack/scripts/colors-dark.sh --red

gnome-terminal --hide-menubar --working-directory=/ -e zsh
gnome-terminal --hide-menubar -e zsh
gnome-terminal --hide-menubar --working-directory=/home/kana/.config/ -e zsh
gnome-terminal --hide-menubar --working-directory=/home/kana/Trabajo/ -e zsh