#!/usr/bin/env bash

#
# Configuración BSPWM creada por https://github.com/srmai
# Copyright (C) 2022-2024 Carlos Ayala <carlosadrian.cg2@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
#

## General ---------------------------------------------------#

## URl del directorio de Bspwm
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Configuracion de dimensiones del monitor ---------------------------#

## Directorio de configuraciones de ARandR
ARDIR="$HOME/.config/bspwm/xrandr"

#Determinamos la cantidad de monitores conectados usando el comando "xrandr"
num_monitors=$(xrandr | grep " connected" | wc -l)

# Si hay dos monitores conectados, ejecutamos el script
if [ "$num_monitors" -eq 2 ]; then
	## Selección de resolucion
	bash "$ARDIR"/2domonitor.sh
fi

## Configuración de tema ---------------------------------------------#

## Carga los colores del tema actual
source "$BSPDIR"/themes/kana.bash
## Coloca un fondo de pantalla aleatorio
num_aleatorio=$RANDOM
# Calculamos el resto de la división de este número entre 11 para que de un numero del 1 al 10
numero=$((num_aleatorio % 10 + 1))
if [ $numero -eq 1 ]; then
  feh --bg-fill "$wallpaper"
elif [ $numero -eq 2 ]; then
  dwall -s earth
elif [ $numero -eq 3 ]; then
  feh --bg-fill "$wallpaper"
elif [ $numero -eq 4 ]; then
  dwall -s earth
elif [ $numero -eq 5 ]; then
  feh --bg-fill "$wallpaper"
elif [ $numero -eq 6 ]; then
  dwall -s forest
elif [ $numero -eq 7 ]; then
  dwall -s factory
elif [ $numero -eq 8 ]; then
  dwall -s mountains
elif [ $numero -eq 9 ]; then
  feh --bg-fill "$wallpaper"
elif [ $numero -eq 10 ]; then
  dwall -s desert
else
  feh --bg-fill "$wallpaper"
fi

## Get the colors from theme file
BACKGROUND="$background"
GREEN="$color2"
BLUE="$color4"
MAGENTA="$color5"

## Bspwm apariencia
#Grosor del borde
CURRENT_BORDER='1'
#Separacion del borde
CURRENT_GAP='10'

CURRENT_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manager Workspaces
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

## Apply bspwm configurations
bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Administrar todas las ventanas no administradas restantes de una sesión anterior.
bspc wm --adopt-orphans

## Reglas de ventana ----------------------------------------------#

# Quitar todas las reglas primero
bspc rule -r *:*

## 1 > terminal (siempre abra la terminal en el espacio de trabajo-1)
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a gnome-terminal desktop='^1' follow=on focus=on

## 2 > web (siempre abra el navegador web en el espacio de trabajo-2)
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

## 3 > archivos (siempre abra el administrador de archivos en el espacio de trabajo-3)
bspc rule -a Pcmanfm desktop='^3' follow=on focus=on
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a qBittorrent desktop='^3' follow=on focus=on

## 4 > código (siempre abra los editores en el espacio de trabajo-4)
bspc rule -a Geany desktop='^3' follow=on focus=on
bspc rule -a code-oss desktop='^3' follow=on focus=on
bspc rule -a code desktop='^3' follow=on focus=on

## 5 > office y docs (siempre abra las aplicaciones de office/doc en el espacio de trabajo-5)
bspc rule -a Gucharmap desktop='^5' follow=on focus=on
bspc rule -a Atril desktop='^5' follow=on focus=on
bspc rule -a Evince desktop='^5' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^5' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^5' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^5' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^5' follow=on focus=on
bspc rule -a libreoffice desktop='^5' follow=on focus=on
bspc rule -a Soffice desktop='^5' follow=on focus=on
bspc rule -a libreofficedev desktop='^5' follow=on focus=on
bspc rule -a soffice desktop='^5' follow=on focus=on

## 6 > comunicación (siempre abra las aplicaciones de comunicación en el espacio de trabajo)-6)
bspc rule -a Thunderbird desktop='^6' follow=on focus=on
bspc rule -a TelegramDesktop desktop='^6' follow=on focus=on
bspc rule -a Hexchat desktop='^6' follow=on focus=on

## 7 > medios (siempre abra las aplicaciones de medios en el espacio de trabajo-7)
bspc rule -a Audacity desktop='^7' state=floating follow=on focus=on
bspc rule -a Music desktop='^7' state=floating follow=on focus=on
bspc rule -a MPlayer desktop='^7' state=floating follow=on focus=on
bspc rule -a Lxmusic desktop='^7' state=floating follow=on focus=on
bspc rule -a Inkscape desktop='^7' state=floating follow=on focus=on
bspc rule -a krita desktop='^7' state=floating follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^7' state=floating follow=on focus=on
bspc rule -a obs desktop='^7' state=floating follow=on focus=on

## 8 > sistema (siempre abra las aplicaciones del sistema en el espacio de trabajo-8)
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a Lxappearance desktop='^8' state=floating follow=on focus=on
bspc rule -a Lxtask desktop='^8' state=floating follow=on focus=on
bspc rule -a Lxrandr desktop='^8' state=floating follow=on focus=on
bspc rule -a Arandr desktop='^8' state=floating follow=on focus=on
bspc rule -a System-config-printer.py desktop='^8' state=floating follow=on focus=on
bspc rule -a Pavucontrol desktop='^8' state=floating follow=on focus=on
bspc rule -a Exo-helper-1 desktop='^8' state=floating follow=on focus=on
bspc rule -a Xfce4-power-manager-settings desktop='^8' state=floating follow=on focus=on

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Matar si ya se está ejecutando
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch xsettingsd daemon
#xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Iniciar combinaciones de teclas
sxhkd &

# Habilitar superteclas para el menú
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Habilitar administración de energía
xfce4-power-manager &

# Start mpd
exec mpd &


# Start bspwm scripts

bspcolors
bspbar
bspcomp
bspdunst
bspfloat &

## Cambia la polyBar al inicio
## Directorio de configuración de Polybar
PBDIR="$HOME/.config/bspwm/polybar"
## Selección de Polybar
bash "$PBDIR"/launch.sh --hack
## Tema
bash "$PBDIR"/hack/scripts/colors-dark.sh --red

##Ejecutar aplicaciones al inicio
gnome-terminal --hide-menubar --working-directory=/ -e zsh
gnome-terminal --hide-menubar -e zsh
gnome-terminal --hide-menubar --working-directory=/home/kana/.config/ -e zsh
gnome-terminal --hide-menubar --working-directory=/home/kana/Trabajo/ -e zsh

#Selecciona escritorio de inicio
bspc desktop -f ^1

# Fix cursor
xsetroot -cursor_name left_ptr

# Touchpad configurations
for id in 1 2 3 4 5 7 8 9 10 11 12 13 14 15 16 17 18 19 20
do
  hola=$(xinput | grep 'Touchpad' | grep -w 'id='$id'')
  if [ -z "$hola"]
  then
    echo ''
  else
    for (( i=300; i<=400; i++ )); do
      activar=$(xinput list-props $id | grep 'Tapping Enabled ('$i')' | grep -w '('$i')')
      if [[ $activar == *"Tapping Enabled ("* ]];
      then
        xinput set-prop $id $i 1
        xinput list-props $id        
      else
        echo ''
      fi
    done
 fi
done
