#!/usr/bin/env bash

#
# Atajos de teclado creados por https://github.com/srmai
#

##---------- Rofi Launcher & Menus ----------##

# Rofi Themes Menu
ctrl + alt + t
	sh ~/.config/bspwm/rofi/bin/themes

# Rofi Menus/Applets
super + {w,n,r,s}
	sh ~/.config/bspwm/rofi/bin/{windows,mpd,asroot,screenshot}
super + x
    bash ~/.config/bspwm/polybar/hack/scripts/powermenu.sh
super + shift + w
	sh ~/.config/bspwm/rofi/bin/windows

# Rofi App Launcher
super + shift + d
	rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/bspwm/polybar/hack/scripts/rofi/launcher.rasi

super + d
    rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/bspwm/polybar/hack/scripts/rofi/launcher.rasi

# make sxhkd reload its configuration files:
super + shift + r
	pkill -USR1 -x sxhkd
#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + c
	bspc node -c
# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction

super + {_,shift + }{Left,Down,Up,Right}
       bspc node -{f,s} {west,south,north,east}

# Change focus to next window, including floating window
alt + {_,shift + }Tab
	bspc node -f {next.local,prev.local}

# Switch to last opened workspace
super + {Tab,grave}
	bspc {node,desktop} -f last

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# move/resize
#

# move a floating window
super + ctrl + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


##---------- System Keys ----------##

# Take a screenshot
Print
	scrot -b -d 0 '%Y:%m:%d:%H:%M:%S.png' -e 'mv $f ~/Imágenes/'
	
# Take screenshot in 5 second
alt + Print	
	scrot -b -d 5 '%Y:%m:%d:%H:%M:%S.png' -e 'mv $f ~/Imágenes/'

# Take screenshot in 10 second
shift + Print	
	scrot -b -d 0 '%Y:%m:%d:%H:%M:%S.png' -e 'mv $f ~/Imágenes/'

# Brighness control
XF86MonBrightness{Up,Down}
	brightness{ --inc, --dec}
	
# Volume control
XF86Audio{RaiseVolume,LowerVolume}
	pactl set-sink-volume @DEFAULT_SINK@ { +10%, -10%}

XF86AudioMute
	pactl set-sink-volume @DEFAULT_SINK@ 0%

XF86AudioMicMute
	volume --toggle-mic
	
# Music control
XF86Audio{Next,Prev,Play,Stop}
	mpc {next,prev,toggle,stop}



# ---------------------------------------------
# CUSTOM
# ---------------------------------------------

# Google-Chrome

super + shift + n
	google-chrome

# terminal emulator
super + Return
	gnome-terminal --hide-menubar
super + shift + t
  gnome-terminal --full-screen

# Gestor de archivos
super + shift + a
  thunar

# Visual Studio Code
super + shift + c
  code

# Github
super + shift + g
  github